import streamlit as st
import pandas as pd
import os

# === 1. Page Configuration ===
st.set_page_config(page_title="AI Behavior Analysis Dashboard", layout="wide", page_icon="📺")

st.title("📺 Home Media Usage Analysis Report")
st.markdown("Analysis results using **Twelve Labs Marengo (Visual Search)** & **Pegasus (Generative Video Understanding)**")

# === 2. Load Data ===
DATA_FILE = "analysis_result.csv"

@st.cache_data
def load_data():
    if not os.path.exists(DATA_FILE):
        return None
    data = pd.read_csv(DATA_FILE)
    return data

df = load_data()

if df is None:
    st.warning("⚠️ Analysis data file (`analysis_result.csv`) not found.")
    st.info("Please run the backend analysis script first:\n\n`python analysis.py`")
    st.stop()

# Helper: Format seconds to MM:SS
def format_time(seconds):
    try:
        m, s = divmod(float(seconds), 60)
        return f"{int(m):02d}:{int(s):02d}"
    except:
        return str(seconds)

df['Start'] = df['start_time'].apply(format_time)
df['End'] = df['end_time'].apply(format_time)
df['Duration'] = df['end_time'] - df['start_time']

# === 3. Key Metrics ===
st.subheader("Key Metrics")
col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Total Detected Actions", f"{len(df)} counts")

with col2:
    avg_duration = df['Duration'].mean()
    st.metric("Avg. Action Duration", f"{avg_duration:.1f} sec")

with col3:
    video_id_display = df['video_id'].iloc[0] if not df.empty else "-"
    st.metric("Target Video ID", f"{video_id_display[:8]}...") # Show first 8 chars

st.divider()

# === 4. Filter & Data Table ===
st.subheader("📋 Detailed Action Log (Pegasus Analysis)")

# Search Bar
params_container = st.container()
with params_container:
    search_term = st.text_input("🔍 Search Keywork (e.g., 'sitting', 'phone')", "")

if search_term:
    filtered_df = df[df['ai_description'].str.contains(search_term, case=False, na=False)]
else:
    filtered_df = df

# Display Dataframe
display_cols = ['Start', 'End', 'ai_description', 'confidence_score', 'Duration']
st.dataframe(
    filtered_df[display_cols],
    use_container_width=True,
    column_config={
        "Start": "Start Time",
        "End": "End Time",
        "ai_description": "AI Description (Pegasus)",
        "confidence_score": st.column_config.ProgressColumn(
            "Confidence", format="%.2f", min_value=0, max_value=100
        ),
        "Duration": st.column_config.NumberColumn("Duration (s)", format="%.1f")
    },
    hide_index=True
)

# === 5. Visualizations ===
st.subheader("📊 Visualizations")
tab1, tab2 = st.tabs(["Timeline", "Duration Distribution"])

with tab1:
    st.caption("Distribution of detected actions over video timeline")
    # Simple scatter plot for timeline
    # Using start_time on X axis, Duration on Y axis, Color by Confidence
    st.scatter_chart(
        filtered_df,
        x='start_time',
        y='Duration',
        color='confidence_score',
        size='Duration',
        use_container_width=True
    )

with tab2:
    st.caption("Histogram of action durations")
    st.bar_chart(filtered_df['Duration'])

# Footer
st.markdown("---")
st.caption("Generated by Twelve Labs Agentic Assistant")
